name: Prettier Check

on:
  push:
    branches:
      - main
      - developer
  pull_request:
<<<<<<< HEAD
    branches:
      - main
      - developer
=======
    types: [opened, synchronize, reopened]
>>>>>>> origin/developer

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
<<<<<<< HEAD

=======
>>>>>>> origin/developer
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          same_commit: true #ensures that the pipeline does not overwrite the current commit
          prettier_version: 3.3.3
<<<<<<< HEAD
          prettier_options: --write **/*.{js,jsx,ts,tsx,json,md,css}
=======
          prettier_options: --write **/*.{js,jsx,ts,tsx,json,css}
>>>>>>> origin/developer
          github_token: ${{ secrets.GITHUBTOKEN }}
