name: Prettier Check

on:
  push:
    branches: [main, develop, ci/test]
  pull_request:
    branches: [main, develop]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.{js,ts,tsx,json,md,css}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
