name: Prettier Check

on:
  push:
    branches: [main, develop, ci/test]
  pull_request:
    branches: [main, develop]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.9.0"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: |
          npm run lint:check &&
          npm run lint:fix
